### ISSUE TITLE
member lookup

### ISSUE THREAD

**Issue by jkldgoefgkljefogeg** [APNIC-net/rdapd#47]
How can I look up resources by APNIC member https://www.apnic.net/about-apnic/organization/structure/members/ ?

ASN has mnt-by:  APNIC-HM which is odd

there is no whois support (member <> maintainer) for member / organization?

**Comment by tomhrr** [comment]
Sorry about the delay here.  You can query for the organisation name in Whois, to find the corresponding organisation object.  For example:

    $ whois -hwhois.apnic.net -- Asia Pacific Network Information Centre
    % [whois.apnic.net]
    % Whois data copyright terms    http://www.apnic.net/db/dbcopyright.html

    % Information related to 'ORG-APNI1-AP'

    organisation:   ORG-APNI1-AP
    org-name:       Asia Pacific Network Information Centre
    remarks:        APNIC Infrastructure Services
    country:        AU
    address:        6 Cordelia Street
    phone:          +61-7-3858-3100
    fax-no:         +61-7-3858-3199
    e-mail:         noc@apnic.net
    mnt-ref:        APNIC-HM
    mnt-by:         APNIC-HM
    last-modified:  2018-06-06T05:06:58Z
    source:         APNIC

    ...
    $

Once it's found, you can then do an inverse query for their resources:

    $ whois -hwhois.apnic.net -- -i org ORG-APNI1-AP -K -r -T inetnum,inet6num,aut-num | grep -e 'inetnum' -e 'inet6num' -e 'aut-num'
    inetnum:        202.12.28.0 - 202.12.28.255
    inetnum:        202.12.29.0 - 202.12.29.255
    inetnum:        202.12.31.0 - 202.12.31.255
    inetnum:        203.119.0.0 - 203.119.0.255
    inetnum:        203.119.100.0 - 203.119.103.255
    inetnum:        203.119.104.0 - 203.119.111.255
    inetnum:        203.119.76.0 - 203.119.76.255
    inetnum:        203.119.77.0 - 203.119.77.255
    inetnum:        203.119.86.0 - 203.119.86.255
    inetnum:        203.119.95.0 - 203.119.95.255
    inetnum:        220.247.144.0 - 220.247.159.255
    inet6num:       2001:dc0:2000::/35
    inet6num:       2001:dc0:4000::/35
    inet6num:       2001:dc0:8000::/35
    ...

Organisation objects are not currently supported in RDAP, though we do have plans to implement that.

> ASN has mnt-by: APNIC-HM which is odd

ASNs are maintained by APNIC-HM so that end-users cannot make arbitrary changes to them, or delete them.

> there is no whois support (member <> maintainer) for member /
> organization?

No, there is no authoritative link between accounts and maintainers. However, fetching the resources associated with an account and then taking the non-APNIC-HM maintainers from those objects should give a reasonable approximation of the maintainers that a given account is using.

If you have more questions along these lines, it is better to contact helpdesk@apnic.net, since it's the standard channel for this sort of thing.  Alternatively, there is apnic-services@apnic.net, which is a public mailing list for discussing technical aspects of APNIC services (see https://www.apnic.net/community/participate/mailinglists/#apnic-services).
